name: flutter_examen_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    go_router: ^7.0.0
      cupertino_icons: ^1.0.2
        http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

assets:
  - assets/data.json

